### ISSUE TITLE
Document what restrictions can be set on the API key

### ISSUE THREAD

**Issue by NatoBoram** [pcouy/YoutubeAutotranslateCanceler#2]
Hey! Once an API key is generated, it would be a good idea to restrict it to certain scopes. You should probably add in the [README.md](https://github.com/pcouy/YoutubeAutotranslateCanceler/blob/master/README.md#how-to-use) how to appropriately restrict the API key.

![image](https://user-images.githubusercontent.com/10495562/49194383-e9307380-f350-11e8-8200-83442d56b910.png)

**Comment by pcouy** [comment]
I have updated the [README.md](https://github.com/pcouy/YoutubeAutotranslateCanceler/blob/master/README.md) with more detailed instructions (845d4ca)
