### ISSUE TITLE
Do not work with Classic interface

### ISSUE THREAD

**Issue by LeoKesler** [pcouy/YoutubeAutotranslateCanceler#20]
Hi,
The script do not work if using the classic interface of Youtube. 

```
Failed to find main video description! userscript.html:137:42
Checking main video and 0 video titles! userscript.html:105:21
Failed to find main video description! userscript.html:137:42
Checking main video and 0 video titles! userscript.html:105:21
Failed to find main video description! userscript.html:137:42
Checking main video and 0 video titles! userscript.html:105:21
```
Using the "modern"   interface, the script works correctly. 

Tested with Firefox nightly.

**Comment by pcouy** [comment]
How do you switch to the classic interface? I will look into this when I have some time

**Comment by LeoKesler** [comment]
I edited the youtube cookie for make the classic interface default again. Check the first comment:

https://github.com/YePpHa/YouTubeCenter/issues/2444

Thank you.

**Comment by pcouy** [comment]
I do not intend to support compatibility with other scripts/extensions/hacks. Since you had to edit a cookie and make it read-only, I consider re-enabling the classic interface a hack and will not fix this.

However, I will leave this issue open if someone wants to make a pull request for it. @Seneral has made a more full-featured fork of this script, maybe try asking him

**Comment by Seneral** [comment]
Sorry, not been using the old interface either. I've kind of ditched YouTube for most  of my video needs anyway in favour of a custom website (FlagPlayer if you're interested).
Might look into it though, it's most likely just a quick change in HTML selectors.

**Comment by LeoKesler** [comment]
OK, fair enough. Thank you.

**Comment by HRudyPlayZ** [comment]
Can confirm this still doesn't work with the Classic Layout, kind of sad as both the newer layout and title translations are very bad, awful edits to YouTube. Would it be possible to update the script to point to the classic's layout elements instead if it's enabled?
