### ISSUE TITLE
Suddenly doesn't work anymore

### ISSUE THREAD

**Issue by Xiarno** [pcouy/YoutubeAutotranslateCanceler#23]
Title is as that. It just doesn't work anymore.

**Comment by lukasfink1** [comment]
It seems like Greasemonkey removed the old `GM_setValue` and `GM_getValue` functions. Merging pull request #21 fixes this problem for me.

**Comment by Xiarno** [comment]
> It seems like Greasemonkey removed the old `GM_setValue` and `GM_getValue` functions. Merging pull request #21 fixes this problem for me.

Ok, I'm not a coder here. I'm just giving feedback on things. I have no single idea how to do this so I'm not gonna even try.

**Comment by lukasfink1** [comment]
You can either wait for someone with write permission to merge the pull request and then update your script or [install knoxfighter’s fork](https://github.com/knoxfighter/YoutubeAutotranslateCanceler/raw/Update/use-modern-storage/AntiTranslate.user.js) and then change line 82 with the Greasemonkey editor (Greasemonkey icon → “Youtube Autotranslate Canceler” → “edit”) to
`        var links = Array.prototype.slice.call(document.getElementsByTagName("yt-formatted-string")).filter( a => {`
 (don’t forget to save).
Notice that you then have to reinstall the script from this repo when there is a new update (so you might want to watch this repo).

**Comment by Xiarno** [comment]
> You can either wait for someone with write permission to merge the pull request and then update your script or [install knoxfighter’s fork](https://github.com/knoxfighter/YoutubeAutotranslateCanceler/raw/Update/use-modern-storage/AntiTranslate.user.js) and then change line 82 with the Greasemonkey editor (Greasemonkey icon → “Youtube Autotranslate Canceler” → “edit”) to
> ` var links = Array.prototype.slice.call(document.getElementsByTagName("yt-formatted-string")).filter( a => {`
> (don’t forget to save).
> Notice that you then have to reinstall the script from this repo when there is a new update (so you might want to watch this repo).

Doesn't work. Or atleast I get an error
![YBAdAo3i18](https://user-images.githubusercontent.com/24660485/74613390-14c98600-50dc-11ea-8067-a6f127ec9145.png)

**Comment by pcouy** [comment]
I have merged #21, problem should be fixed. I'm closing the issue but feel free to re-open if you still can't get it to work.
Thanks for the feedback

**Comment by Xiarno** [comment]
Nope, still doesn't work :/

**Comment by lukasfink1** [comment]
Works for me. Did you manually reinstall it? If not, click [here](https://github.com/pcouy/YoutubeAutotranslateCanceler/raw/master/AntiTranslate.user.js).

**Comment by Xiarno** [comment]
I reinstalled it, did the update and everything. Still doesn't work.
It seemed to work at first but now it doesn't.

**Comment by pcouy** [comment]
Can you tell me what browser and what user script management extension you are using?

**Comment by Xiarno** [comment]
> Can you tell me what browser and what user script management extension you are using?

Google Chrome & Tampermonkey.
