### ISSUE TITLE
Project is missing a license

### ISSUE THREAD

**Issue by lukasfink1** [pcouy/YoutubeAutotranslateCanceler#24]
It could be that I just overlooked it, but it seems to me as if this project currently has no license. This theoretically makes it illegal for everyone except the author to do almost anything with this script—including simply using it as it’s intended. So please add a license to this project. See [here](https://choosealicense.com/no-permission/) for more info on this issue.

**Comment by pcouy** [comment]
Thank you ! Fixed in f094512
