### ISSUE TITLE
Doesn't work on opened videos

### ISSUE THREAD

**Issue by NatoBoram** [pcouy/YoutubeAutotranslateCanceler#3]
https://www.youtube.com/watch?v=UwYSWAlAewc

[![image](https://user-images.githubusercontent.com/10495562/49194498-6d82f680-f351-11e8-85f7-4bbdba0821c7.png)](https://www.youtube.com/watch?v=UwYSWAlAewc)

**Comment by pcouy** [comment]
It has been fixed by @Seneral in commit 1478b29
