### ISSUE TITLE
Namespace isn't changed

### ISSUE THREAD

**Issue by NatoBoram** [pcouy/YoutubeAutotranslateCanceler#4]
The [namespace](https://tampermonkey.net/documentation.php#_namespace) should be changed, probably to `https://github.com/pcouy/YoutubeAutotranslateCanceler/`

https://github.com/pcouy/YoutubeAutotranslateCanceler/blob/b6121885bf679c60ebb51730f237ddb1b603d96d/AntiTranslate.user.js#L3

**Comment by pcouy** [comment]
Thanks, done !
