### ISSUE TITLE
YouTube Auto Play support

### ISSUE THREAD

**Issue by Seneral** [pcouy/YoutubeAutotranslateCanceler#6]
Information of the previous video is carried over when using Youtube auto play, which will result in descriptions from the previous videos still being displayed for all following ones. 

There are two problems with this: Not only doesn't the script recognise the new video and replace the video description, but youtube itself also doesn't replace the modified description at all...

That last one is worrying me tbh, it seems Youtube notices changes to the description and explicitly does not overwrite them.

Obvious solution would be to detect a video change (easiest through URL), discard all caches and reevaluate the whole page.

Also worthy of note is that it seems that ONLY the description is affected, nothing else. No clue why though.

**Comment by Seneral** [comment]
Nvm, I see you already posted a fix... had not updated yet.

One new problem with that is that it will also update when the notification amount is appended to the window title (like "(4) VideoTitle - YouTube"). Easy fix is to remove that again of course, or to change on URL change only, not title change.

**Comment by pcouy** [comment]
I tried using `location.href` instead of `document.title` but it did not work for an unknown reason. That's why I used the title, but I did not think of notifications altering the title.

**Comment by Seneral** [comment]
I will test, failed yesterday cause I did not get any new notifications lol

**Comment by Seneral** [comment]
Fixed in latest PR #12 !
Btw why did location.href not work for you? Works fine for me, implemented it in PR, so may need to check that.
If that does not work for you for some reason, it might not work for others aswell. For me it works now atleast...

**Comment by Seneral** [comment]
Fixed in latest commit
